updated config file #35, fix #37, improved get_liturgia fx

diff --git a/build b/build
--- a/build
+++ b/build
@@ -3,14 +3,9 @@
 # esporta le variabili d'ambiente
 set -a
 
-# constants
-DATA_DIR="data"
-LITURGIA_URL="https://www.chiesacattolica.it/liturgia-del-giorno/?data-liturgia="
-LITURGIA_DIR="risorse/lezionari/liturgie"
-PATH_CALENDARIO_LITURGICO="data/calendari_liturgici/calendario_2019-2050.csv"
-LITURGIA_FILE_BASENAME="liturgia"
-SUGGERIMENTI_FILE_BASENAME="suggerimenti"
-HOMEPAGE_PATH="docs/index.md"
+# import variables
+source <(grep = scripts/config.ini)
+
 
 
 # importing functions
@@ -21,35 +16,39 @@ source ./scripts/convert_iso_to_extended_date
 source ./scripts/convert_iso_to_weekday
 
 # crea cartella data se non esiste
-if [ ! -d "$DATA_DIR" ]; then
-  mkdir $DATA_DIR
+if [ ! -d "$PATH_DATA" ]; then
+  mkdir $PATH_DATA
+  echo "✅ Creata cartella data"
 fi
 
 # crea cartella liturgie se non esiste
-if [ ! -d "$LITURGIA_DIR" ]; then
-  mkdir $LITURGIA_DIR
+if [ ! -d "$PATH_LITURGIE" ]; then
+  mkdir $PATH_LITURGIE
+  echo "✅ Creata cartella liturgie"
 fi
 
 # rendi eseguibili gli script
 chmod +x ./scripts/*
 
-# scarica anagrafica
-# get_anagrafica > $DATA_DIR/anagrafica_canti.csv
-# echo "✅ Scaricata anagrafica canti"
-
-# scarica testi
-# ./scripts/db_downloader
-# echo "✅ Scaricati testi canti"
+# se vuoi scaricare anagrafica canti e testi canti devi usare
+# db_downloader
+# con le opportune istruzioni e autenticazioni
 
 # scarica liturgia
-LITURGIA_DATE=$(get_next_sunday)
-liturgia_data_iso=$LITURGIA_DATE
+liturgia_data_iso=$(get_next_sunday)
+liturgia_data_yyyymmdd=$(date -d $liturgia_data_iso +%Y%m%d)
 liturgia_data_estesa=$(convert_iso_to_extended_date "$liturgia_data_iso")
 liturgia_weekday=$(convert_iso_to_weekday "$liturgia_data_iso")
 
-get_liturgia $LITURGIA_DATE $PATH_CALENDARIO_LITURGICO $LITURGIA_DIR > $LITURGIA_DIR/../$LITURGIA_FILE_BASENAME-latest.txt
+get_liturgia "$liturgia_data_iso" "$PATH_CALENDARIO_LITURGICO" "$PATH_LITURGIE" > $PATH_LITURGIA
 
-echo "📅 Data della prossima liturgia domenicale: $(date -d $LITURGIA_DATE +%d/%m/%Y)"
+# se get liturgia ritorna errore, esci
+if [ $? -eq 1 ]; then
+  echo "❌ $0: Errore durante il recupero della liturgia" >&2
+  exit 1
+fi
+
+echo "📅 Data della prossima liturgia domenicale: $(date -d $liturgia_data_iso +%d/%m/%Y)"
 echo "✅ Individuata liturgia"
 
 # run suggeritore
@@ -59,10 +58,10 @@ echo "✅ Individuata liturgia"
 ./scripts/build_page
 
 # organize files 
-cp $DATA_DIR/$SUGGERIMENTI_FILE_BASENAME-latest.csv $DATA_DIR/$SUGGERIMENTI_FILE_BASENAME-$LITURGIA_DATE.csv
+cp $PATH_DATA/$FILE_BASENAME_SUGGERIMENTI-latest.csv $PATH_DATA/$FILE_BASENAME_SUGGERIMENTI-$liturgia_data_yyyymmdd.csv
 
 suggerimenti_on_archive_path="docs/archivio/$liturgia_data_estesa.md"
-cp $HOMEPAGE_PATH "$suggerimenti_on_archive_path"
+cp $PATH_HOMEPAGE "$suggerimenti_on_archive_path"
 
 # clean suggerimenti on archive
 line_end=$(cat "$suggerimenti_on_archive_path" | grep -n ":material-music" | cut -d: -f1)
diff --git a/scripts/get_liturgia b/scripts/get_liturgia
--- a/scripts/get_liturgia
+++ b/scripts/get_liturgia
@@ -1,58 +1,63 @@
 #!/bin/bash
 
-# get_liturgia wants 3 input
-# 1. date in the format YYYY-MM-DD (e.g., 2024-06-02)
-# 2. $path_calendario_liturgico
-# 3. $path_liturgie
-
-# output of the function
-# liturgy text on terminal stdout
-
-check_liturgia_date(){
-        # check if the input is provided
-    if [ -z "$1" ]; then
-        echo "Please provide the date in the format YYYY-MM-DD (e.g. $0 2024-06-02)"
-        return 1
-    fi
-
-    # check if the input is a valid iso date
-    if ! date -d $1 > /dev/null 2>&1; then
-        echo "Please provide a valid date in the format YYYY-MM-DD (e.g., $0 2024-06-02)"
-        return 1
-    fi
-    
-}
-
-# transform the code into a function get_liturgia
 get_liturgia() {
+    # overview: this function will get the liturgy text for a given date
+
+    # input:
+    # 1. date in the format YYYY-MM-DD (e.g., 2024-06-02)
+    # 2. path del calendario liturgico csv file
+    # 3. path della cartella contenente i file di testo delle liturgie
+    # output:
+
+    # liturgy text on terminal stdout
 
     # check if all the inputs are provided
     if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
-        echo "Please provide the date in the format YYYY-MM-DD (e.g. $0 2024-06-02)"
-        echo "Please provide the path to the calendario liturgico csv file"
-        echo "Please provide the path to the liturgie folder"
+        echo "❌ ${FUNCNAME[0]}: Missing arguments" >&2
+        echo "Please provide the date in the format YYYY-MM-DD (e.g. ${FUNCNAME[0]} 2024-06-02)" >&2
+        echo "Please provide the path to the calendario liturgico csv file" >&2
+        echo "Please provide the path to the liturgie folder" >&2
         return 1
     fi
 
-    path_calendario_liturgico=$2
-    path_liturgie=$3
-
-    check_liturgia_date $1
-
-    # if check fails, return 1
-    if [ $? -eq 1 ]; then
+    # check date
+    if ! date -d $1 > /dev/null 2>&1; then
+        echo "❌ ${FUNCNAME[0]}: Please provide a valid date in the format YYYY-MM-DD (e.g., ${FUNCNAME[0]} 2024-06-02)" >&2
         return 1
     fi
 
     liturgia_data_iso=$1
+    path_calendario_liturgico=$2
+    path_liturgie=$3
+
+    
+
+    # se $path_calendario_liturgico non esiste, ritorna errore
+    if [ ! -f $path_calendario_liturgico ]; then
+        echo "❌ ${FUNCNAME[0]}: File $path_calendario_liturgico not found" >&2
+        return 1
+    fi
 
     # filtra con miller usando $liturgia_data_iso come data
     id_liturgia=$(mlr --csv filter '$date == "'"$liturgia_data_iso"'"' $path_calendario_liturgico | mlr --csv cut -f id_liturgia | mlr --c2n cat)
 
+    # se non trova l'id della liturgia, ritorna errore
+    if [ -z "$id_liturgia" ]; then
+        echo "❌ ${FUNCNAME[0]}: Liturgia not found" >&2
+        return 1
+    fi
+
+    # build filename_liturgia usando questa logica $path_liturgie/$id_liturgia.txt
+    filename_liturgia=$path_liturgie/$id_liturgia.txt
+    echo $filename_liturgia >&2
+
+    # se $path_liturgie/$id_liturgia.txt non esiste, ritorna errore
+    if [ ! -f "$filename_liturgia" ]; then
+        echo "❌ ${FUNCNAME[0]}: File "$filename_liturgia" not found" >&2
+        return 1
+    fi
+
     # display text and remove more than one empty line
-    cat $path_liturgie/$id_liturgia.txt | sed '/^$/N;/^\n$/D'
+    cat $filename_liturgia | sed '/^$/N;/^\n$/D'
 
 }
-
-
-
