added auth to db_downloader #16

diff --git a/scripts/db_downloader b/scripts/db_downloader
--- a/scripts/db_downloader
+++ b/scripts/db_downloader
@@ -1,19 +1,32 @@
 #!/bin/bash
 
+# questo script usa get_text_by id e get_anagrafica per scaricare tutti i canti dal sito librettocanti.it
+
 # constants
-ANAGRAFICA_FILE="data/anagrafica_canti.csv"
-IDS_FILE="data/id_canti.txt"
 CANTI_DIR="canti"
 
+# output
+ANAGRAFICA_FILE="data/anagrafica_canti.csv"
+IDS_FILE="data/id_canti.txt"
+
 # importa funzioni
-source ./scripts/get_text_from_id
+source ./scripts/get_text_by_id
 source ./scripts/get_anagrafica
 
-# controlla se esiste il file anagrafica 
-if [ ! -f $ANAGRAFICA_FILE ]; then
-   echo "File $ANAGRAFICA_FILE non trovato! Lo sto scaricando..."
-   get_anagrafica > ANAGRAFICA_FILE
+# get access token
+token=$(curl -s https://www.librettocanti.it/api/get_access_token/$USERNAME/$PASSWORD | jq -r ".access_token")
+
+# se non riesce a ottenere il token, esce
+if [ -z $token ]; then
+   echo "❌ Errore: non è stato possibile ottenere l'access token. Controlla le credenziali inserite."
+   exit 1
 fi
+
+# controlla se esiste il file anagrafica 
+# if [ ! -f $ANAGRAFICA_FILE ]; then
+#    echo "File $ANAGRAFICA_FILE non trovato! Lo sto scaricando..."
+#    get_anagrafica > ANAGRAFICA_FILE
+# fi
 
 # se la cartella canti non esiste, creala
 if [ ! -d $CANTI_DIR ]; then
@@ -21,19 +34,25 @@ if [ ! -d $CANTI_DIR ]; then
 fi
 
 # aggiorna l'anagrafica
-get_anagrafica > $ANAGRAFICA_FILE
+get_anagrafica $token > $ANAGRAFICA_FILE
+
+# controlla se l'anagrafica è vuota
+if [ ! -s $ANAGRAFICA_FILE ]; then
+   echo "❌ Errore: l'anagrafica è vuota. Controlla le credenziali inserite."
+   exit 1
+fi
 
 # usa mlr per estrarre solo la colonna id_canti
 mlr --csv cut -f id_canti $ANAGRAFICA_FILE | tail -n +2 | sed 's/"//g' > $IDS_FILE
 
-# per ogni id_canto, usa get_text_from_id per estrarre il testo e salvarlo in CANTI_DIR con nomefile id_canto.txt
+# per ogni id_canto, usa get_text_by_id per estrarre il testo e salvarlo in CANTI_DIR con filename id_canto.txt
 total_lines=$(wc -l < $IDS_FILE)
 current_line=1
 
-echo "Ho trovato $total_lines canti da scaricare. Inizio il download..."
+echo "🛠 Ho trovato $total_lines canti da scaricare. Inizio il download..."
 
 while read id_canto; do
-   get_text_from_id $id_canto > $CANTI_DIR/$id_canto.txt
+   get_text_by_id $id_canto $token > $CANTI_DIR/$id_canto.txt
    echo "Progresso: $current_line/$total_lines"
    ((current_line++))
 done < $IDS_FILE
@@ -42,4 +61,6 @@ done < $IDS_FILE
 rm $IDS_FILE
 
 # fine
-echo "Finito!"
+echo "✅ Finito!"
+echo "📂 I testi dei canti sono stati scaricati nella cartella $CANTI_DIR"
+echo "📄 L'anagrafica dei canti è stata salvata in $ANAGRAFICA_FILE"
