reorganized files, using custom liturgies #23 #24

diff --git a/scripts/get_liturgia b/scripts/get_liturgia
--- a/scripts/get_liturgia
+++ b/scripts/get_liturgia
@@ -1,56 +1,58 @@
 #!/bin/bash
 
-# input of the function
-# $1 = date in the format YYYYMMDD (e.g., 20240602)
+# get_liturgia wants 3 input
+# 1. date in the format YYYY-MM-DD (e.g., 2024-06-02)
+# 2. $path_calendario_liturgico
+# 3. $path_liturgie
 
 # output of the function
 # liturgy text on terminal stdout
 
-# testare anche questo https://www.vaticannews.va/it/vangelo-del-giorno-e-parola-del-giorno/2024/05/26.html
-
 check_liturgia_date(){
         # check if the input is provided
     if [ -z "$1" ]; then
-        echo "Please provide the date in the format YYYYMMDD (e.g., $0 20240602)"
+        echo "Please provide the date in the format YYYY-MM-DD (e.g. $0 2024-06-02)"
         return 1
     fi
 
-    # check if the input is a valid date
-    if ! [[ $1 =~ ^[0-9]{8}$ ]]; then
-        echo "The date is not in the correct format. Please provide the date in the format YYYYMMDD (e.g., 20240602)"
+    # check if the input is a valid iso date
+    if ! date -d $1 > /dev/null 2>&1; then
+        echo "Please provide a valid date in the format YYYY-MM-DD (e.g., $0 2024-06-02)"
         return 1
     fi
+    
 }
 
 # transform the code into a function get_liturgia
 get_liturgia() {
 
-    # constants
-    LITURGIA_URL="https://www.chiesacattolica.it/liturgia-del-giorno/?data-liturgia="
+    # check if all the inputs are provided
+    if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
+        echo "Please provide the date in the format YYYY-MM-DD (e.g. $0 2024-06-02)"
+        echo "Please provide the path to the calendario liturgico csv file"
+        echo "Please provide the path to the liturgie folder"
+        return 1
+    fi
+
+    path_calendario_liturgico=$2
+    path_liturgie=$3
 
     check_liturgia_date $1
 
-    # concatenate the LITURGIA_URL with the date
-    LITURGIA_URL="$LITURGIA_URL$1"
+    # if check fails, return 1
+    if [ $? -eq 1 ]; then
+        return 1
+    fi
 
-    # scrape the content of the LITURGIA_URL
-    curl -sL $LITURGIA_URL \
-    | scrape -be '.cci-liturgia-giorno-section-content' \
-    | sed 's/<p\/>//g' | sed 's/^ *//g' | sed 's/></> </g' | sed 's/<br\/>/ <br\/>/g' \
-    | xq -r '.. | objects | .["#text"]? // empty'
+    liturgia_data_iso=$1
+
+    # filtra con miller usando $liturgia_data_iso come data
+    id_liturgia=$(mlr --csv filter '$date == "'"$liturgia_data_iso"'"' $path_calendario_liturgico | mlr --csv cut -f id_liturgia | mlr --c2n cat)
+
+    # display text and remove more than one empty line
+    cat $path_liturgie/$id_liturgia.txt | sed '/^$/N;/^\n$/D'
+
 }
 
-get_liturgia_rif(){
-    # constants
-    LITURGIA_URL="https://www.chiesacattolica.it/liturgia-del-giorno/?data-liturgia="
-    
-    check_liturgia_date $1
 
-    # concatenate the LITURGIA_URL with the date
-    LITURGIA_URL="$LITURGIA_URL$1"
 
-    curl -sL $LITURGIA_URL \
-    | scrape -be '.bibbiaedu-linked' \
-    | sed 's/<p\/>//g' | sed 's/^ *//g' | sed 's/></> </g' | sed 's/<br\/>/ <br\/>/g' \
-    | xq  '[.html.body.span[].a | {url:."@href", data_target:."@data-target", text:."#text"}]'
-}
